# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "fsdocs-tool"; version = "18.1.1"; sha256 = "0yqs2hxva0vcrwa9fzkkymnrxlpbzywwb2vpdpivr589lyyp1n3s"; })
  (fetchNuGet { pname = "FSharp.Core"; version = "6.0.1"; sha256 = "0qks2aadkhsffg9a6xq954ll9xacnph852avd7ljh9n2g6vj06qj"; })
  (fetchNuGet { pname = "SixLabors.Fonts"; version = "2.0.4"; sha256 = "1ays7y9w0fcqdjbc6bxjqr6xf7zndqf2hxhdv0pvphyv8z7lm33w"; })
  (fetchNuGet { pname = "SixLabors.ImageSharp"; version = "3.1.4"; sha256 = "0cs6wfx74rwp88m5arci04ldv2s92kpif28ykfm9ig17h9a8gsnc"; })
  (fetchNuGet { pname = "SixLabors.ImageSharp.Drawing"; version = "2.1.3"; sha256 = "1ihcpg7d61dnnb3s6z2ariykb78zawhfi6k20pf369r845sygfip"; })
]
